apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: ingress-gateway-k3s
spec:
  selector:
    istio: ingressgateway
  servers:
    - port: 
        number: 80
        name: http
        protocol: http2
      hosts:
        - "*.local"
  
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: echo-virtualservice-bar
spec:
  hosts:
    - "bar.local"
  gateways:
    - ingress-gateway-k3s
  http:
    - route:
      - destination:
          host: echo-service
          subset: bar
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: echo-virtualservice-foo
spec:
  hosts:
    - "foo.local"
  gateways:
    - ingress-gateway-k3s
  http:
    - route:
      - destination:
          host: echo-service
          subset: foo
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: echo-destinationrule
spec:
  host: echo-service
  subsets:
    - name: foo
      labels:
        version: foo
    - name: bar
      labels:
        version: bar