apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: echo-virtualservice
spec:
  hosts:
    - echo-service

  http:
    - fault:
        # delay:
        #   fixedDelay: 10s
        #   percentage:
        #     value: 100
        abort:
          httpStatus: 500
          percentage:
            value: 25
      route:
      - destination:
          host: echo-service
          subset: all
