apiVersion: v1
kind: Service
metadata:
  name: echo-service
spec:
  selector:
    app: echo
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 80
    # nodePort: 30001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-foo
spec:
  selector:
    matchLabels:
      app: echo
  replicas: 5
  template:
    metadata:
      labels:
        app: echo
        version: foo
    spec:
      containers:
      - name: echo-foo
        image: leonardonatali/echo
        env:
          - name: MESSAGE
            value: "Hello from FOO"
        resources:
          limits:
            memory: "64Mi"
            cpu: "50m"
        ports:
        - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-bar
spec:
  selector:
    matchLabels:
      app: echo
  replicas: 5
  template:
    metadata:
      labels:
        app: echo
        version: bar
    spec:
      containers:
      - name: echo-bar
        image: leonardonatali/echo
        env:
          - name: MESSAGE
            value: "Hello from BAR"
        resources:
          limits:
            memory: "64Mi"
            cpu: "50m"
        ports:
        - containerPort: 80