apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: echo-destinationrule
spec:
  host: echo-service
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
  subsets:
    - name: foo
      labels:
        version: foo
      trafficPolicy:
        loadBalancer:
          simple: LEAST_CONN
    - name: bar
      labels:
        version: bar