apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: echo-virtualservice
spec:
    hosts:
      - echo-service
    http:
      - route:
        - destination:
            host: echo-service
            subset: foo
          weight: 90
        - destination:
            host: echo-service
            subset: bar
          weight: 10
